# Generated by Django 5.1.5 on 2025-03-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entry_year',
            field=models.IntegerField(blank=True, choices=[(2020, '2020년'), (2021, '2021년'), (2022, '2022년'), (2023, '2023년'), (2024, '2024년'), (2025, '2025년')], default=2025, null=True),
        ),
    ]
